baseurl = "https://stats4good.github.io/gesem/"
title = "Grupo de Estudo da Subnotificação de Estupro em Mulheres"
theme = "hugo-universal-theme"
languageCode = "pt-br"
publishDir = "docs"
#relativeurls = true
canonifyURLs = false
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pt"
# Enable comments by entering your Disqus shortname

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-107006863-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Define the number of posts per page
paginate = 15

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
    
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

#[[menu.main]]
#    name = "Contato"
#    url  = "/contact/"
#    weight = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/stats4good"
    pre = "<i class='fa fa-2x fa-github'></i>"


[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:stats4good@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/gesem/blog/"
    author = "gesem"
    defaultKeywords = ["S4G", "R", "Data Science"]
    defaultDescription = ""
    about_us = "<p>Grupo de estudantes de pós graduação em estatística, com intuito de usar a ciência em prol da sociedade.</p>"
    copyright = "Copyright (c) 2017 , Stats4Good; all rights reserved."
    ##-- Estilo ----
    style = "violet"
    ##-- Formato da data ----
    date_format = "02/01/2006"
    ##-- Highlight ----
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "monokai"
    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""
    logo = "img/logo.png"
    address = """<p><strong>Stats4Good</strong>
        <br> stats4good@gmail.com
        <br>Avenida Presidente Antônio Carlos, 6627
        <br> Belo Horizonte - MG - Pampulha
        <br>
        <strong>Brasil</strong>
      </p>
      """
    latitude = "-19.8691265"
    longitude = "-43.9647344"

[Permalinks]
    blog = "/blog/:year/:month/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us stats4good@gmail.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Depoimentos"
    subtitle = "O que pensam os membros e colaboradores sobre nosso grupo."


[params.recent_posts]
    enable = true
    title = "Blog"
    subtitle = "Últimas postagens do nosso blog"

[params.favicons]
    enable = true
    
[params.Paginator.Next.URL]
    url  = "{{ .Site }}/blog/2"
